/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufp.inf.aedlp.project.gui;

import edu.princeton.cs.algs4.DijkstraSP;
import edu.princeton.cs.algs4.In;
import edu.princeton.cs.algs4.RedBlackBST;
import edu.princeton.cs.algs4.SeparateChainingHashST;
import edu.ufp.inf.aedlp.project.Aeroporto;
import edu.ufp.inf.aedlp.project.Aviao;
import edu.ufp.inf.aedlp.project.Ligacao;
import edu.ufp.inf.aedlp.project.Main;
import edu.ufp.inf.aedlp.project.Rede;
import edu.ufp.inf.aedlp.project.Viagem;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author ZeeCunha
 */
public class Interface extends javax.swing.JFrame {
    
    /**
     *
     */
    protected static Rede rede;

    /**
     *
     */
    protected static Main main;
    /*
     * St's Principais 
     */
        
    // red-black trees
    RedBlackBST<String, Aviao> aviaoST = new RedBlackBST<>();
    RedBlackBST<String, Viagem> viagemST = new RedBlackBST<>();
        
    //Separate Chaining Hash 
    SeparateChainingHashST<String, Aeroporto> aeroportoST = new SeparateChainingHashST<>();
    
    //Hash map
    HashMap<Integer,String> hmap = new HashMap<>();
    HashMap<String, Integer> hmapInvert = new HashMap<>();

    /**
     *
     * @return
     */
    public RedBlackBST<String, Aviao> getAviaoST() {
        return aviaoST;
    }

    /**
     *
     * @param aviaoST
     */
    public void setAviaoST(RedBlackBST<String, Aviao> aviaoST) {
        this.aviaoST = aviaoST;
    }

    /**
     *
     * @return
     */
    public RedBlackBST<String, Viagem> getViagemST() {
        return viagemST;
    }

    /**
     *
     * @param viagemST
     */
    public void setViagemST(RedBlackBST<String, Viagem> viagemST) {
        this.viagemST = viagemST;
    }

    /**
     *
     * @return
     */
    public SeparateChainingHashST<String, Aeroporto> getAeroportoST() {
        return aeroportoST;
    }

    /**
     *
     * @param aeroportoST
     */
    public void setAeroportoST(SeparateChainingHashST<String, Aeroporto> aeroportoST) {
        this.aeroportoST = aeroportoST;
    }

    /**
     *
     * @return
     */
    public HashMap<Integer, String> getHmap() {
        return hmap;
    }

    /**
     *
     * @param hmap
     */
    public void setHmap(HashMap<Integer, String> hmap) {
        this.hmap = hmap;
    }

    /**
     *
     * @return
     */
    public HashMap<String, Integer> getHmapInvert() {
        return hmapInvert;
    }

    /**
     *
     * @param hmapInvert
     */
    public void setHmapInvert(HashMap<String, Integer> hmapInvert) {
        this.hmapInvert = hmapInvert;
    }
    
    
    
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        Main.loadFromFileAeroporto(aeroportoST, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\airports.txt");
        Main.loadFromFileAviao(aviaoST, aeroportoST, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\airplanes.txt");
        Main.loadFromFileViagem(viagemST, aeroportoST, aviaoST, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\viagem.txt");
        Main.loadFromFileLinksTradutor(hmap, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\links(tradutor).txt");
        Main.loadFromFileLinksTradutorInverted(hmapInvert, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\links(tradutor).txt");
        
        //Carregar aviões para a combo Box de avioes
        for (String id_aviao : aviaoST.keys()) {
            Aviao a = aviaoST.get(id_aviao);
            //System.out.println(p.toString()); 
            listaviao.addItem("" + a.getId_aviao());
        }
        
        //Carregar aeroportos para a combo box de aeroportos
        for (String id_aeroporto : aeroportoST.keys()) {
            Aeroporto a = aeroportoST.get(id_aeroporto);
            //System.out.println(p.toString()); 
            listaeroporto.addItem("" + a.getCodigo_aeroporto());
            partida.addItem("" + a.getCodigo_aeroporto());
            destino.addItem("" + a.getCodigo_aeroporto());
        }
        
        //Carregar viagens para a combo box de viagens
        for (String id_viagens : viagemST.keys()) {
            Viagem v = viagemST.get(id_viagens);
            //System.out.println(p.toString()); 
            listaviagens.addItem("" + v.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        listaviagens = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        id_viagemF = new javax.swing.JTextField();
        aero_init = new javax.swing.JTextField();
        aero_dest = new javax.swing.JTextField();
        aviao_viagem = new javax.swing.JTextField();
        passageiros_viagem = new javax.swing.JTextField();
        data_init = new javax.swing.JTextField();
        data_dest = new javax.swing.JTextField();
        hora_init = new javax.swing.JTextField();
        hora_dest = new javax.swing.JTextField();
        altitude_viagem = new javax.swing.JTextField();
        distancia_viagem = new javax.swing.JTextField();
        criarViagem = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        apagarViagem = new javax.swing.JButton();
        caminhoMaisCurto1 = new javax.swing.JButton();
        maisPassageiros = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        partida = new javax.swing.JComboBox<>();
        destino = new javax.swing.JComboBox<>();
        caminhoMaisCurto = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        custoTemporal = new javax.swing.JButton();
        custoConsumo = new javax.swing.JButton();
        conexao = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        listaviao = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        compA = new javax.swing.JTextField();
        velocidade = new javax.swing.JTextField();
        altitude = new javax.swing.JTextField();
        distancia = new javax.swing.JTextField();
        cod_aeroporto = new javax.swing.JTextField();
        passageiros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rext = new javax.swing.JLabel();
        deposito = new javax.swing.JTextField();
        viagens = new javax.swing.JTextField();
        rext1 = new javax.swing.JLabel();
        criarAviao = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        apagarAviao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        listaeroporto = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nome2 = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        continente = new javax.swing.JTextField();
        classificacao = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        avioes = new javax.swing.JTextField();
        viagens2 = new javax.swing.JTextField();
        criarAeroporto = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        apagarAero = new javax.swing.JButton();
        maisTrafego = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        listaviagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaviagensActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("ID:");

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Aero. Inicio:");

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Aero. Destino:");

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Passageiros:");

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Aviao:");

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Data Destino:");

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Data Inicio:");

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Hora Inicio:");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Hora Destino:");

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Altitude:");

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Distancia:");

        criarViagem.setText("Criar Viagem");
        criarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarViagemActionPerformed(evt);
            }
        });

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ufp/inf/aedlp/project/gui/logo2.jpg"))); // NOI18N
        jLabel36.setText("José Cunha - 28018 - LP2 - AED2");

        apagarViagem.setText("Apagar Viagem");
        apagarViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarViagemActionPerformed(evt);
            }
        });

        caminhoMaisCurto1.setText("Caminho mais curto");
        caminhoMaisCurto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoMaisCurto1ActionPerformed(evt);
            }
        });

        maisPassageiros.setText("Mais Passageiros");
        maisPassageiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisPassageirosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(id_viagemF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aero_init, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aero_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aviao_viagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passageiros_viagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(data_init, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(data_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hora_init, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hora_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(distancia_viagem))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(altitude_viagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(listaviagens, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(criarViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apagarViagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maisPassageiros)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(caminhoMaisCurto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel36)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaviagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarViagem)
                    .addComponent(apagarViagem)
                    .addComponent(maisPassageiros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(id_viagemF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(aero_init, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(aero_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(aviao_viagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(passageiros_viagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(data_init, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(data_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(hora_init, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(hora_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(altitude_viagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(distancia_viagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(caminhoMaisCurto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Viagens", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        caminhoMaisCurto.setText("Caminho mais curto");
        caminhoMaisCurto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoMaisCurtoActionPerformed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ufp/inf/aedlp/project/gui/A.png"))); // NOI18N

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ufp/inf/aedlp/project/gui/B.png"))); // NOI18N

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ufp/inf/aedlp/project/gui/logo2.jpg"))); // NOI18N
        jLabel37.setText("José Cunha - 28018 - LP2 - AED2");

        custoTemporal.setText("Rota mais rápida");
        custoTemporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoTemporalActionPerformed(evt);
            }
        });

        custoConsumo.setText("Rota mais económica");
        custoConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoConsumoActionPerformed(evt);
            }
        });

        conexao.setText("Verificar conexão");
        conexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caminhoMaisCurto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(partida, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(69, 69, 69))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel37)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conexao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custoConsumo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addComponent(custoTemporal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(partida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(caminhoMaisCurto)
                .addGap(18, 18, 18)
                .addComponent(custoTemporal)
                .addGap(18, 18, 18)
                .addComponent(custoConsumo)
                .addGap(18, 18, 18)
                .addComponent(conexao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ligações", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        listaviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaviaoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Modelo:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nome:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Companhia A.:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Velocidade C.:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Altitude C. :");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Distancia Max.:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Cod. Aeroporto:");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cap. Passageiros:");

        rext.setForeground(new java.awt.Color(0, 0, 0));
        rext.setText("Cap. Deposito:");

        rext1.setForeground(new java.awt.Color(0, 0, 0));
        rext1.setText("N. Viagens:");

        criarAviao.setText("Criar novo avião");
        criarAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarAviaoActionPerformed(evt);
            }
        });

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ufp/inf/aedlp/project/gui/logo2.jpg"))); // NOI18N
        jLabel38.setText("José Cunha - 28018 - LP2 - AED2");

        apagarAviao.setText("Apagar Avião");
        apagarAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarAviaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaviao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rext, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(rext1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(criarAviao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apagarAviao))
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(velocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altitude, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_aeroporto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passageiros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viagens, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 145, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel38)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarAviao)
                    .addComponent(apagarAviao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(velocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_aeroporto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passageiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rext)
                    .addComponent(deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rext1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Avião", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        listaeroporto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaeroportoActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nome:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Codigo:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Cidade:");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Pais:");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Classificação:");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Continente:");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("N. Aviões:");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("N. Viagens:");

        criarAeroporto.setText("Criar Aeroporto");
        criarAeroporto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarAeroportoActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ufp/inf/aedlp/project/gui/logo2.jpg"))); // NOI18N
        jLabel30.setText("José Cunha - 28018 - LP2 - AED2");

        apagarAero.setText("Apagar Aeroporto");
        apagarAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarAeroActionPerformed(evt);
            }
        });

        maisTrafego.setText("Mais Trafego");
        maisTrafego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisTrafegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listaeroporto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(criarAeroporto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apagarAero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maisTrafego))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viagens2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(avioes, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(classificacao, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(continente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pais, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cidade, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(codigo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nome2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaeroporto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(criarAeroporto)
                    .addComponent(apagarAero)
                    .addComponent(maisTrafego))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(continente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(avioes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(viagens2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aeroporto", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Outros", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Função/botão para listar todos os aviões
     * 
     */
    private void listaviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaviaoActionPerformed
        String comboAviao = ((String) listaviao.getSelectedItem().toString());
        Aviao a = aviaoST.get(comboAviao);
        id.setText(String.valueOf(a.getId_aviao()));
        modelo.setText(a.getModelo());
        nome.setText(String.valueOf(a.getNome()));
        compA.setText(String.valueOf(a.getCompanhia_aerea()));
        velocidade.setText(String.valueOf(a.getVelocidade_cruzeiro()));
        altitude.setText(String.valueOf(a.getAltitude_cruzeiro()));
        distancia.setText(String.valueOf(a.getDistancia_maxima()));
        cod_aeroporto.setText(String.valueOf(a.getCod_aeroporto()));
        passageiros.setText(String.valueOf(a.getCapacidade_de_passageiros()));
        deposito.setText(String.valueOf(a.getCapacidade_de_deposito()));
        viagens.setText(String.valueOf(a.getAviaoViagemST().size()));
    }//GEN-LAST:event_listaviaoActionPerformed
     /**
     * Função/botão para listar todos os aeroportos
     * 
     */
    private void listaeroportoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaeroportoActionPerformed
        String comboAeroporto = ((String) listaeroporto.getSelectedItem().toString());
        Aeroporto a = aeroportoST.get(comboAeroporto);
        nome2.setText(String.valueOf(a.getNome_aeroporto()));
        codigo.setText(a.getCodigo_aeroporto());
        cidade.setText(String.valueOf(a.getCidade()));
        pais.setText(String.valueOf(a.getPais()));
        continente.setText(String.valueOf(a.getContinente()));
        classificacao.setText(String.valueOf(a.getClassificacao()));
        avioes.setText(String.valueOf(a.getAeroportoAviaoST().size()));
        viagens2.setText(String.valueOf(a.getAeroportoViagemST().size()));
    }//GEN-LAST:event_listaeroportoActionPerformed
   /**
     * Função/botão para listar todas as viagens 
     * 
     */
    private void listaviagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaviagensActionPerformed
        String comboViagens = ((String) listaviagens.getSelectedItem().toString());
        Viagem v = viagemST.get(comboViagens);
        id_viagemF.setText(String.valueOf(v.getId()));
        aero_init.setText(String.valueOf(v.getAeroportoInit()));
        aero_dest.setText(String.valueOf(v.getAeroportoDest()));
        aviao_viagem.setText(String.valueOf(v.getAviao()));
        passageiros_viagem.setText(String.valueOf(v.getPassageiros()));
        data_init.setText(String.valueOf(v.getDataInit()));
        data_dest.setText(String.valueOf(v.getDataDest()));
        hora_init.setText(String.valueOf(v.getHoraInit()));
        hora_dest.setText(String.valueOf(v.getHoraDest()));
        altitude_viagem.setText(String.valueOf(v.getAltitude()));
        distancia_viagem.setText(String.valueOf(v.getDistancia()));
    }//GEN-LAST:event_listaviagensActionPerformed
    /**
     * Função/botão para retornar o caminho mais curto entre 2 aeroportos
     * 
     */
    private void caminhoMaisCurtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoMaisCurtoActionPerformed

        In in = new In("C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\links.txt");
        int V = Integer.parseInt(in.readLine());   //vertices   
        rede = new Rede(V);
        int E = Integer.parseInt(in.readLine());
        System.out.println("E = " + E); //edges
        String line = in.readLine();
        while(line!= null) {
            
            String[] texto = line.split(";");
            int v = Integer.parseInt(texto[0]); //posicao do id no txt
            int w = Integer.parseInt(texto[1]); //posicao do modelo no txt
            double c1 = Double.parseDouble(texto[2]); //posicao da distancia no txt
            double c2 = Double.parseDouble(texto[3]); //posicao do vento no txt
            double c3 = Double.parseDouble(texto[4]); //posicao da altitude no txt
            
            rede.addEdge(new Ligacao(v,w,c1,c2,c3));    //criar nova ligacao
            
            //System.out.println(w + " " + v + " " + c1 + " " + c2 + " " + c3);
            line = in.readLine();
        }
        //System.out.println(r.toString());
        in.close(); //parar a leitura
        
        String part = (String)partida.getSelectedItem();    //receber aeroporto de partida
        System.out.println("part="+part);
        String dest = (String)destino.getSelectedItem();    //receber aeroporto de destino
        System.out.println("dest="+dest);
        int s1_id = hmapInvert.get(part); //converter aeroporto de partida string to int
        System.out.println("s1_id=" + s1_id);   
        int s2_id = hmapInvert.get(dest); //converter aeroporto de destino string to int
        System.out.println("s2_id=" + s2_id);   
        
        System.out.println("Result= " + rede.myDijkstraSP(hmap, viagemST, aeroportoST, aviaoST, rede, s1_id, s2_id, "DISTANCIA").distTo(s2_id));
        //System.out.println("result="+ rede.shortestPath(aeroportoST, rede, s1_id, s1_id));
        
        JOptionPane.showMessageDialog(rootPane, rede.shortestPath(hmap, aeroportoST, aviaoST, rede, s1_id, s2_id,"DISTANCIA" ));
        
    }//GEN-LAST:event_caminhoMaisCurtoActionPerformed
     /**
     * Função/botão para criar um novo avião
     * 
     */
    private void criarAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarAviaoActionPerformed
        
        String idA=id.getText();
        String modeloA = modelo.getText();
        String nomeA = nome.getText();
        String compAA = compA.getText();
        String velocidadeA = velocidade.getText();
        int altitudeA = Integer.parseInt(altitude.getText());
        String distanciaA = distancia.getText();
        String codAA = cod_aeroporto.getText();
        int passageirosA = Integer.parseInt(passageiros.getText());
        int depositoA = Integer.parseInt(deposito.getText());
        
        //Verifica se o codigo do aeroporto existe na BD
        if (aeroportoST.contains(codAA)) {
            Aviao a = new Aviao(idA, modeloA, nomeA, compAA, velocidadeA, altitudeA, distanciaA, codAA, passageirosA, depositoA);
            aviaoST.put(idA, a);
            Rede.saveAviao(aviaoST, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\airplanes.txt");    //gravar no txt
            listaviao.addItem(""+a.getId_aviao());  //adicionar o novo aviao à comboBox
            JOptionPane.showMessageDialog(rootPane,"Avião adicionado com sucesso!"); 
        }else{
            JOptionPane.showMessageDialog(rootPane,"O código do aeroporto não existe, insira um válido!"); 
        }  
        
        
        
    }//GEN-LAST:event_criarAviaoActionPerformed
     /**
     * Função/botão para criar um novo aeroporto
     * 
     */
    private void criarAeroportoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarAeroportoActionPerformed
        
        String nomeAP= nome2.getText();
        String codAP = codigo.getText();
        String cidadeAP = cidade.getText();
        String paisAP = pais.getText();
        String continenteAP = continente.getText();
        String classificacaoAP = classificacao.getText();
        
        //Verifica se o codigo do aeroporto existe na BD
        if (aeroportoST.contains(codAP)) {
            Aeroporto ap = new Aeroporto(nomeAP, codAP, cidadeAP, paisAP, continenteAP, classificacaoAP);
            aeroportoST.put(codAP, ap);
            Rede.saveAeroporto(aeroportoST, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\airports.txt"); //gravar no txt
            listaeroporto.addItem(""+ap.getCodigo_aeroporto()); //adicionar o novo aviao à comboBox
            JOptionPane.showMessageDialog(rootPane,"Aeroporto adicionado com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane,"O Código de aeroporto inserido já existe!");
        }
        
        
    }//GEN-LAST:event_criarAeroportoActionPerformed
    /**
     * Função/botão para criar uma nova viagem
     * 
     */
    private void criarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarViagemActionPerformed
        String idV= id_viagemF.getText();
        String aeroInit = aero_init.getText();
        String aeroDest = aero_dest.getText();
        String aviaoID = aviao_viagem.getText();
        int passageiroV = Integer.parseInt(passageiros_viagem.getText());
        String dataInit = data_init.getText();
        String dataDest = data_dest.getText();
        String horaInit = hora_init.getText();
        String horaDest = hora_dest.getText();
        int altitudeV = Integer.parseInt(altitude_viagem.getText());
        int distanciaV = Integer.parseInt(distancia_viagem.getText());
        
        //Verifica se o codigo do aeroporto existe na BD
        if (aeroportoST.contains(aeroInit) && aeroportoST.contains(aeroDest) && aviaoST.contains(aviaoID)) {
        
              Viagem v = new Viagem(idV, aeroInit, aeroDest, aviaoID, passageiroV, dataInit, dataDest,horaInit,horaDest,altitudeV,distanciaV);
              viagemST.put(idV, v);
              Rede.saveViagem(viagemST, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\viagem.txt"); //grava rno txt
              listaviagens.addItem(""+v.getId()); //listar no novo aviao na comboBox
              JOptionPane.showMessageDialog(rootPane,"Viagem adicionada com sucesso!");
        }else{
            JOptionPane.showMessageDialog(rootPane,"Dados inválidos!");
        }
    }//GEN-LAST:event_criarViagemActionPerformed
    /**
     * Função/botão para apagar uma viagem dado um id
     * 
     */
    private void apagarViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarViagemActionPerformed
        
        String delete = id_viagemF.getText();
        System.out.println(delete);
        
        for (String idV : viagemST.keys()) {
            Viagem v = (Viagem) viagemST.get(idV); //recebe o id da viagem
            if (v.getId().equals(delete)) { //se for igual, 
                viagemST.delete(idV);   //delete
         }
        }
            Rede.saveViagem(viagemST, "C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\viagem.txt"); //gravar
            int index = listaviagens.getSelectedIndex();
            
            JOptionPane.showMessageDialog(rootPane,"Viagem removida com sucesso!");
            listaviagens.remove(index);
        
    }//GEN-LAST:event_apagarViagemActionPerformed
    /**
     * Função/botão para apagar um aviao dado um id
     * 
     */
    private void apagarAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarAviaoActionPerformed
        String delete = id.getText();
        System.out.println(delete);
        
        for (String idA : aviaoST.keys()) {
            Aviao a = (Aviao) aviaoST.get(idA); //recebe o id da viagem
            if (a.getId_aviao().equals(delete)) {
                aviaoST.delete(idA);
         }
        }
            Rede.saveAviao(aviaoST,"C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\airplanes.txt");
           JOptionPane.showMessageDialog(rootPane,"Avião removido com sucesso!");
    }//GEN-LAST:event_apagarAviaoActionPerformed
     /**
     * Função/botão para apagar um aeroporto dado um id
     * 
     */
    private void apagarAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarAeroActionPerformed
        String delete = codigo.getText();
        System.out.println(delete);
        
        for (String idAP : aeroportoST.keys()) {
            Aeroporto ap = (Aeroporto) aeroportoST.get(idAP); //recebe o id da viagem
            if (ap.getCodigo_aeroporto().equals(delete)) {
                aeroportoST.delete(idAP);
         }
        }
            Rede.saveAeroporto(aeroportoST,"C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\airports.txt");
           JOptionPane.showMessageDialog(rootPane,"Aeroporto removido com sucesso!");
    }//GEN-LAST:event_apagarAeroActionPerformed
    /**
     * Função/botão para listar o caminho mais curto entre duas viagens.txt
     * 
     */
    private void caminhoMaisCurto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoMaisCurto1ActionPerformed
        //Carregar ficheiros que estão no txt de links
        
        In in = new In("C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\links.txt");
        int V = Integer.parseInt(in.readLine());  //vertices    
        rede = new Rede(V); //nova rede
        int E = Integer.parseInt(in.readLine());    //edges
        System.out.println("E = " + E);
        String line = in.readLine();
        while(line!= null) {
            
            String[] texto = line.split(";");
            int v = Integer.parseInt(texto[0]); //posicao do id no txt
            int w = Integer.parseInt(texto[1]); //posicao do modelo no txt
            double c1 = Double.parseDouble(texto[2]); //posicao da distancia no txt
            double c2 = Double.parseDouble(texto[3]); //posicao do vento no txt
            double c3 = Double.parseDouble(texto[4]); //posicao da altitude no txt
            
            
            rede.addEdge(new Ligacao(v,w,c1,c2,c3));    //nova ligacao
            
            //System.out.println(w + " " + v + " " + c1 + " " + c2 + " " + c3);
            line = in.readLine();
        }
        //System.out.println(r.toString());
        in.close(); //parar
        
        String part = (String)aero_init.getText();  //string aeroporto aeroporto partida
        //System.out.println("part="+part);
        String dest = (String)aero_dest.getText();  //string aeroporto aeroporto destino
        //System.out.println("dest="+dest);
        int s1_id = hmapInvert.get(part); //converter aeroporto partida de string para int
        //System.out.println("s1_id=" + s1_id);
        int s2_id = hmapInvert.get(dest); //converter aeroporto destino de string para int
        //System.out.println("s2_id=" + s2_id);
        //System.out.println("result="+ rede.shortestPath(aeroportoST, rede, s1_id, s2_id));
        
         JOptionPane.showMessageDialog(rootPane, rede.shortestPath(hmap, aeroportoST, aviaoST, rede, s1_id, s2_id,"DISTANCIA" ));
        
    }//GEN-LAST:event_caminhoMaisCurto1ActionPerformed
     /**
     * Função/botão para imprimir qual o aeroporto com + trafego 
     * 
     */
    private void maisTrafegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisTrafegoActionPerformed
       int count=0, count2=0;
       String cod = "";
     
     //Percorrer todos os aeroportos
     for(String codigo_aeroporto: aeroportoST.keys()){ 
         Aeroporto a = (Aeroporto) aeroportoST.get(codigo_aeroporto);
         //System.out.println("a.codigo_aeroporto");
         count = 0;
         //percorrer todas as viagens
         for(String dataInit : viagemST.keys()){
             Viagem v = viagemST.get(dataInit);
             //comparar aeroportos do aeroporto txt com aeroportos do viagens.txt (inicio e fim)
             if(a.getCodigo_aeroporto().compareTo(v.aeroportoInit) == 0|| a.getCodigo_aeroporto().compareTo(v.aeroportoDest) == 0){
                 count++;   //cada vez que aparece, incrimenta 1 ao count
         }
     }	 
		 if ( count2 < count){	
                     
		        count2 = count;
			cod = a.getCodigo_aeroporto();  //codigo do aeroporto
		 }
         }
     
     JOptionPane.showMessageDialog(rootPane, "O " + cod + " é o aeroporto com + trafego (" + count2 +")!");
    }//GEN-LAST:event_maisTrafegoActionPerformed
    /**
     * Função/botão para imprimir a viagem com mais passageiros
     * 
     */
    private void maisPassageirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisPassageirosActionPerformed
        int primeiro = 0;
        String idMP = null;
        for(String viagem: viagemST.keys()){ 
            Viagem v = viagemST.get(viagem);
 
            if(v.getPassageiros() > primeiro){  //se o n de passageiros foi maior do que o primeiro n de passageiros 
                primeiro = v.getPassageiros();  //guarda o maior valor
                idMP = v.id;  //"carregar" o id da viagem com mais passageiros
            }  
        }
        JOptionPane.showMessageDialog(rootPane, "O id " + idMP + " é a viagem com + passageiros (" + primeiro +")!");
    }//GEN-LAST:event_maisPassageirosActionPerformed
    /**
     * Função/botão que chama o myDijkstra para calcular o tempo de viagem para cada aviao num dado aeroporto de partida
     * 
     */
    private void custoTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoTemporalActionPerformed

        
        In in = new In("C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\links.txt");
        int V = Integer.parseInt(in.readLine());    //vertices    
        rede = new Rede(V); //nova rede
        int E = Integer.parseInt(in.readLine());    //edges
        System.out.println("E = " + E);
        String line = in.readLine();
        while(line!= null) {
            
            String[] texto = line.split(";");
            int v = Integer.parseInt(texto[0]); //posicao do id no txt
            int w = Integer.parseInt(texto[1]); //posicao do modelo no txt
            double c1 = Double.parseDouble(texto[2]); //posicao da distancia no txt
            double c2 = Double.parseDouble(texto[3]); //posicao do vento no txt
            double c3 = Double.parseDouble(texto[4]); //posicao da altitude no txt
            
            
            rede.addEdge(new Ligacao(v,w,c1,c2,c3));    //nova ligacao
            
            //System.out.println(w + " " + v + " " + c1 + " " + c2 + " " + c3);
            line = in.readLine();
        }
        //System.out.println(r.toString());
        in.close(); //parar
        
        String part = (String)partida.getSelectedItem();    //string do aeroporto de partida
        System.out.println("part="+part);
        String dest = (String)destino.getSelectedItem();    //string do aeroporto de destino
        System.out.println("dest="+dest);
        int s1_id = hmapInvert.get(part); //string do aeroporto de partida para int
        System.out.println("s1_id=" + s1_id);
        int s2_id = hmapInvert.get(dest); //string do aeroporto de destino para int
        System.out.println("s2_id=" + s2_id);
       
         JOptionPane.showMessageDialog(rootPane, "A rota escolhida -  \n" + rede.myDijkstraSP(hmap, viagemST, aeroportoST, aviaoST, rede, s1_id, s2_id, "DURACAO").pathTo(s2_id)+";");
         JOptionPane.showMessageDialog(rootPane, "Duração - " + rede.myDijkstraSP(hmap, viagemST, aeroportoST, aviaoST, rede, s1_id, s2_id, "DURACAO").distTo(s2_id)+" horas!");

    }//GEN-LAST:event_custoTemporalActionPerformed
     /**
     * Função/botão que chama o myDijkstra para calcular o consumo de viagem para cada aviao num dado aeroporto de partida
     * 
     */
    private void custoConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoConsumoActionPerformed
        
        
        In in = new In("C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\links.txt");
        int V = Integer.parseInt(in.readLine());        //vertices 
        rede = new Rede(V); //nova rede
        int E = Integer.parseInt(in.readLine());    //edges
        System.out.println("E = " + E);
        String line = in.readLine();
        while(line!= null) {
            
            String[] texto = line.split(";");
            int v = Integer.parseInt(texto[0]); //posicao do id no txt
            int w = Integer.parseInt(texto[1]); //posicao do modelo no txt
            double c1 = Double.parseDouble(texto[2]); //posicao da distancia no txt
            double c2 = Double.parseDouble(texto[3]); //posicao do vento no txt
            double c3 = Double.parseDouble(texto[4]); //posicao da altitude no txt
            
            
            rede.addEdge(new Ligacao(v,w,c1,c2,c3));    //nova ligacao
            
            //System.out.println(w + " " + v + " " + c1 + " " + c2 + " " + c3);
            line = in.readLine();
        }
        //System.out.println(r.toString());
        in.close(); //parar
        
        String part = (String)partida.getSelectedItem();    //string com o aeroporto de partida
        System.out.println("part="+part);
        String dest = (String)destino.getSelectedItem();    //string com o aeroporto de destino
        System.out.println("dest="+dest);
        int s1_id = hmapInvert.get(part); //string com o aeroporto de partida para int
        System.out.println("s1_id=" + s1_id);
        int s2_id = hmapInvert.get(dest); //string com o aeroporto de destino para int
        System.out.println("s2_id=" + s2_id);

         JOptionPane.showMessageDialog(rootPane, "A rota escolhida -  \n" + rede.myDijkstraSP(hmap, viagemST, aeroportoST, aviaoST, rede, s1_id, s2_id, "CONSUMO").pathTo(s2_id)+";");
         JOptionPane.showMessageDialog(rootPane, "Consumo total - " + rede.myDijkstraSP(hmap, viagemST, aeroportoST, aviaoST, rede, s1_id, s2_id, "CONSUMO").distTo(s2_id)+" Litros! ");
    }//GEN-LAST:event_custoConsumoActionPerformed

    private void conexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexaoActionPerformed
        /*
        In in = new In("C:\\Users\\ZeeCunha\\Desktop\\UFP\\4final\\2SEMESTRE\\AEDLP\\data\\links.txt");
        int from = (Integer.parseInt(in.readLine())) - 1 ;
        int flag = 0;
        String type = "";
        Aviao a = null;
        int t;
        
       //primeiro "for()" para percorrer todos os aeroportos
        for(int i = 1 ; i <= from; i++){
        DijkstraSP sp = new DijkstraSP(g, i, a, type);//chamar o diskstra
        //ver se tem caminho para todos os aeroportos
        for (t = 1; t < rede.V(); t++) {
            if (!sp.hasPathTo(t)) {
                flag = 1;
            }
        }
        String cod = hmap.get(i);
        
        if (flag == 0) {
            JOptionPane.showMessageDialog(rootPane, "A rede é conexa");

        } else {
            JOptionPane.showMessageDialog(rootPane, "A rede não é conexa");
        }
        }
        */
    }//GEN-LAST:event_conexaoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aero_dest;
    private javax.swing.JTextField aero_init;
    private javax.swing.JTextField altitude;
    private javax.swing.JTextField altitude_viagem;
    private javax.swing.JButton apagarAero;
    private javax.swing.JButton apagarAviao;
    private javax.swing.JButton apagarViagem;
    private javax.swing.JTextField aviao_viagem;
    private javax.swing.JTextField avioes;
    private javax.swing.JButton caminhoMaisCurto;
    private javax.swing.JButton caminhoMaisCurto1;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField classificacao;
    private javax.swing.JTextField cod_aeroporto;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField compA;
    private javax.swing.JButton conexao;
    private javax.swing.JTextField continente;
    private javax.swing.JButton criarAeroporto;
    private javax.swing.JButton criarAviao;
    private javax.swing.JButton criarViagem;
    private javax.swing.JButton custoConsumo;
    private javax.swing.JButton custoTemporal;
    private javax.swing.JTextField data_dest;
    private javax.swing.JTextField data_init;
    private javax.swing.JTextField deposito;
    private javax.swing.JComboBox<String> destino;
    private javax.swing.JTextField distancia;
    private javax.swing.JTextField distancia_viagem;
    private javax.swing.JTextField hora_dest;
    private javax.swing.JTextField hora_init;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id_viagemF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> listaeroporto;
    private javax.swing.JComboBox<String> listaviagens;
    private javax.swing.JComboBox<String> listaviao;
    private javax.swing.JButton maisPassageiros;
    private javax.swing.JButton maisTrafego;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nome2;
    private javax.swing.JTextField pais;
    private javax.swing.JComboBox<String> partida;
    private javax.swing.JTextField passageiros;
    private javax.swing.JTextField passageiros_viagem;
    private javax.swing.JLabel rext;
    private javax.swing.JLabel rext1;
    private javax.swing.JTextField velocidade;
    private javax.swing.JTextField viagens;
    private javax.swing.JTextField viagens2;
    // End of variables declaration//GEN-END:variables
}
